const fs = require('fs');

const rawList = [
  { name: "Pink Jakirana", price: 100 },
  { name: "Orenge Jakirana", price: 100 },
  { name: "Subra White", price: 100 },
  { name: "Chitra Indian", price: 100 },
  { name: "Purple Star", price: 100 },
  { name: "Miss Alice", price: 100 },
  { name: "Deep Blue", price: 100 },
  { name: "Sunset Red", price: 100 },
  { name: "Sunset Orenge", price: 100 },
  { name: "S.L. Delite", price: 100 },
  { name: "Mira Red", price: 100 },
  { name: "Chitra Cream", price: 100 },
  { name: "Orenge Lady Mary", price: 100 },
  { name: "Partha", price: 100 },
  { name: "Chitra Strif", price: 100 },
  { name: "Orenge Tanglong", price: 100 },
  { name: "White Ball", price: 100 },
  { name: "Dr. Rao", price: 100 },
  { name: "Orenge Mahara", price: 100 },
  { name: "Cherry Blossom", price: 100 },
  { name: "Pink Mahara", price: 100 },
  { name: "Red Mahara", price: 100 },
  { name: "California Gold", price: 100 },
  { name: "Lady Harsen", price: 100 },
  { name: "Wajid Ali Shah", price: 100 },
  { name: "Purple Glavra", price: 100 },
  { name: "White Glavra", price: 100 },
  { name: "Juyel Pich", price: 100 },
  { name: "Juyel Yellow", price: 100 },
  { name: "Juyel Pink", price: 100 },
  { name: "Orenge King", price: 100 },
  { name: "Thima Pink", price: 100 },
  { name: "Monalisa Red", price: 100 },
  { name: "Red Wonder", price: 120 },
  { name: "HB Singh", price: 120 },
  { name: "Pink Formosa", price: 120 },
  { name: "Spider", price: 120 },
  { name: "Ve. Juyel Pink", price: 150 },
  { name: "Begam Sikender", price: 150 },
  { name: "Sufia Indiana", price: 150 },
  { name: "Mondaring", price: 150 },
  { name: "Splash", price: 150 },
  { name: "Thai Delite", price: 150 },
  { name: "Lilac Formusa", price: 150 },
  { name: "Fire Opal", price: 150 },
  { name: "Leepstick", price: 150 },
  { name: "Chili Yellow", price: 150 },
  { name: "Chili Icecream", price: 150 },
  { name: "Chili Red", price: 150 },
  { name: "Chili Pink", price: 150 },
  { name: "Chili White", price: 150 },
  { name: "Chili Orenge", price: 150 },
  { name: "Ornge Glow", price: 150 },
  { name: "Choklet Brown", price: 150 },
  { name: "Choklet Pink", price: 150 },
  { name: "Orenge Luis", price: 150 },
  { name: "Luis Wathen", price: 150 },
  { name: "Monalisa Yellow", price: 150 },
  { name: "Chitra Batik", price: 150 },
  { name: "Tanglong Pink", price: 150 },
  { name: "Tanglong Yellow", price: 150 },
  { name: "Tanglong Purple", price: 150 },
  { name: "Tanglong Red", price: 150 },
  { name: "Torch Butterfly", price: 150 },
  { name: "Sleeping Beauty", price: 150 },
  { name: "Veera Purple", price: 150 },
  { name: "Veera Pink", price: 150 },
  { name: "Veera White", price: 150 },
  { name: "Miss Holland", price: 150 },
  { name: "Silhouette", price: 150 },
  { name: "3 Star", price: 150 },
  { name: "Purple Mix", price: 150 },
  { name: "Sweet Heart", price: 150 },
  { name: "Magic Love", price: 150 },
  { name: "Mahara Roseville", price: 150 },
  { name: "Vishaka", price: 150 },
  { name: "Huge Evans", price: 150 },
  { name: "Bidadari Leepstick", price: 150 },
  { name: "Daniel White", price: 150 },
  { name: "Barbara Krast", price: 150 },
  { name: "Royal Douphin", price: 150 },
  { name: "Butterfly Red", price: 150 },
  { name: "Twister Purple", price: 200 },
  { name: "Bidadari", price: 200 },
  { name: "Butterfly Orenge", price: 200 },
  { name: "Butterfly Yellow", price: 200 },
  { name: "Flame Red", price: 200 },
  { name: "Golden Sunshine", price: 200 },
  { name: "Kristina", price: 200 },
  { name: "Kayata Indiana", price: 200 },
  { name: "Black Monalisa", price: 250 },
  { name: "Purple Butterfly", price: 250 },
  { name: "Tiger Kristina", price: 250 },
  { name: "Verigated Fire Opal", price: 300 },
  { name: "King Opal Variegated", price: 300 },
  { name: "Veg. Flame Red", price: 300 },
  { name: "Monalisa Orange", price: 350 },
  { name: "Kayata Magenda", price: 350 }
];

let html = fs.readFileSync('index.html', 'utf8');

let newPlants = [];
let idCounter = 41;

for (let p of rawList) {
    let finalPrice = p.price <= 250 ? 250 : p.price;
    newPlants.push(`      ,\n      { id: '${idCounter++}', name: '${p.name}', scientificName: 'Bougainvillea ${['Monalisa','Chitra','Mahara'].some(v=>p.name.includes(v)) ? 'spectabilis' : 'glabra'}', price: ${finalPrice}.00, description: 'Premium rare bougainvillea variety from our greenhouse.', careLevel: 'Easy', sunlight: 'Full Sun', category: 'Bougainvillea', image: 'https://images.unsplash.com/photo-1629837586523-28929d0ae7fa?auto=format&fit=crop&q=80&w=800' }`);
}

html = html.replace("    ];", newPlants.join('') + "\n    ];");
html = html.replace("{['All', 'Roses', 'Orchids', 'Ferns', 'Rare']", "{['All', 'Roses', 'Orchids', 'Ferns', 'Bougainvillea', 'Rare']");

fs.writeFileSync('index.html', html);
console.log("Updated index.html successfully with " + newPlants.length + " plants.");
